### PR TITLE
Fix test failure

### PR DESCRIPTION
**Pull request by sjlongland**
This fixes the test failure observed in the last build, possibly due to changes in the test frameworks.

### CODE REVIEW

**Comment by jpic** [comment]
Way to go !

I'd like to merge & release, @Sliim would that be okay for you ?

**Comment by Sliim** [comment]
@jpic Ok for me! Go to merge and release :)
Thanks @sjlongland :+1:

**Comment by Sliim** [comment]
Released in signalslot 0.1.1. Thanks!

**Comment by jpic** [comment]
:guitar:

**Pull request merged**
