### PR TITLE
Thread safety.  Slot class.

### PR DESCRIPTION
**Pull request by sjlongland**
I should probably break this up into a few different commits but essentially this patch set does 3 things:

- Signals can be declared thread-safe, at which point they use a `threading.RLock` to ensure no modifications to the slot list takes place while the list is being iterated over.
- A new Slot class optionally wraps callable functions and supports weak referencing of methods, so as to not break the garbage collector: Slots to objects that have been finalised get dropped by the Signal.
- I've tweaked some of the test cases and coverage settings, notably removing the tests themselves from the coverage as well as one unused exception, and adding a few `# pragma: no cover` statements to select areas.

### CODE REVIEW

**Comment by Sliim** [comment]
Hi @sjlongland 
Thank you for your contrib'! :) 
We will have a look as soon as possible for a potential merging in our master and releasing a new version.

**Comment by sjlongland** [comment]
Well, I've got nearly all of it, still can't figure out how to work this bit:
https://coveralls.io/builds/2423368/source?filename=signalslot%2Fcontrib%2Ftask%2Ftask.py#L59

**Comment by sjlongland** [comment]
Just spotted a possible issue, that is if you mix plain function slots and Slot instances.  I get this:

```
tornado.application: ERROR: Exception in callback <functools.partial object at 0x7fbbecbdc208>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 565, in _run_callback
    ret = callback()
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/stuartl/vrt/projects/metermaster/dal/tests/test_amqp/test_amqpqueue.py", line 54, in _go
    conn.connected_sig.connect(_connected)
  File "/usr/lib64/python2.7/site-packages/signalslot/signal.py", line 98, in connect
    if not self.is_connected(slot):
  File "/usr/lib64/python2.7/site-packages/signalslot/signal.py", line 106, in is_connected
    return slot in self._slots
  File "/usr/lib64/python2.7/site-packages/signalslot/slot.py", line 62, in __eq__
    return self.func == other.func
AttributeError: 'function' object has no attribute 'func'
```

This allows the two to be mixed without issue.

**Comment by sjlongland** [comment]
EUREKA.  That nails it for test cases I think.

**Comment by sjlongland** [comment]
@Sliim: No problems, this might be a better version to go to release with, since it fixes a compatibility issue with Python 2.x in the existing code and the coverage is now complete.

**Comment by jpic** [comment]
Absolutely awesome, thanks a lot.

Will go through a deeper review as soon as the birthday party I'm at is over.

Happy birthday @Sliim bro !!!!

**Comment by jpic** [comment]
I really like the new weak feature, can I merge this @Sliim ? (I see that I have permissions again now but I haven't got the confirmation that it was intentional ^^)

**Comment by jpic** [comment]
Also, I recommend we invite @sjlongland in the core-dev team.

**Comment by Sliim** [comment]
Hi @jpic, yes it was intentional, feel free to merge futures PR ;)
I will merge this PR and release a new version. Thanks for your review!

@sjlongland thanks for your work, and sorry for the delay..

**Comment by sjlongland** [comment]
Hi, no problems, thanks for taking the time to give it a look. :-)

**Pull request merged**
