### PR TITLE
Support for python 3.4

### PR DESCRIPTION
**Pull request by davethecipo**
Hello,

I made a few changes to support python 3.4. The biggest one is copying ``ExitStack`` from contexlib in order to replace contextlib.nested().

I haven't tried this code but all tests pass.

### CODE REVIEW

**Comment by davethecipo** [comment]
Sure.
1. Do you have a preference for the file name?
2. What condition should be used? Maybe something like this?

    try:
        from contextlib import ExitStack
    except ImportError:
        from .NEW_FILE_NAME_HERE import ExitStack

**Comment by davethecipo** [comment]
Hello, now it uses contexter as a replacement, as suggested in the discussion for issue #4. Since I had to revert a few commits, the history looks a little messy. If you want, I can create a new branch and cherry-pick only the last commits, without the reverts.

**Comment by jpic** [comment]
Awesome !

+1

**Comment by Sliim** [comment]
Hi @davethecipo 

Sorry for the late answer.. Merged!
Thanks for your work :+1: 
Thanks @jpic for your review :)

**Pull request merged**
