### PR TITLE
MNT: bump minimum version of python to 3.4 and extend tests

### PR DESCRIPTION
**Pull request by tacaswell**
This removes the dependency on weakrefmethod

### CODE REVIEW

**Comment by fblanchetNaN** [comment]
Hi, could this PR be merged and released?

**Comment by sjlongland** [comment]
Silly question, is this project being maintained?

This library ceases to function in Python 3.11 at the moment due to issue #19, which then means any project that uses it (and there are a few) also stops working.

It's also worth noting that Travis CI is no more, is it worth I fork this PR and add Github actions to run tests?

**Comment by jpic** [comment]
I'm reaching out to @Sliim and will keep you posted, would be great to publish this new version with the current PyPi name

**Comment by sjlongland** [comment]
@jpic @tacaswell … many thanks to you both for your efforts here.

**Pull request merged**
